
GET http://localhost:4001/healthcheck

###

POST http://localhost:4001/trade
content-type: application/json

{
    "buy": "Chaos Orb",
    "sell": "maze-of-the-minotaur-map"
}

###

POST http://trade.localhost:8888/trade
content-type: application/json

{
    "buy": "Chaos Orb",
    "sell": "exalted"
}