{
 "title": "Trade Challenge",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "2s",
 "panels": [
  {
   "title": "Offer Ingestion Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(offers_ingested_challenge[10s])"
    }
   ]
  },
  {
   "title": "Store Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "store_size_challenge" }
   ]
  },
  {
   "title": "Stash Record Ingestion Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(stashes_ingested_challenge[10s])"
    }
   ]
  },
  {
   "title": "Handled Search Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "irate(search_requests[5s])" }
   ]
  }
 ]
}