[workspace]

members = ["indexer", "stash-api", "stash-differ", "trade-ingest", "trade-api"]

[profile.dev]
# Disabling debug info speeds up builds a bunch,
# and we don't rely on it for debugging that much.
debug = false

[profile.release]
debug = true
