
GET http://trade.maximumstock.net/healthcheck

###

POST http://trade.maximumstock.net/trade
content-type: application/json

{
    "buy": "Chaos Orb",
    "sell": "Maze of the Minotaur Map"
}

###

POST http://trade.maximumstock.net/trade
content-type: application/json

{
    "sell": "Dangerous Large Cluster Jewel of the Drake"
}

###

POST http://trade.maximumstock.net/trade
content-type: application/json

{
    "sell": "Chaos Orb",
    "buy": "Exalted Orb",
    "limit": 3
}

###

POST http://trade.maximumstock.net/trade
content-type: application/json

{
    "sell": "Chaos Orb",
    "buy": "Exalted Orb",
    "limit": 3,
    "league": "Hardcore Kalandra"
}
