
GET http://trade.localhost:8888/healthcheck

###

POST http://trade.localhost:8888/trade
content-type: application/json

{
    "buy": "Chaos Orb",
    "sell": "Maze of the Minotaur Map"
}

###

POST http://trade.localhost:8888/trade
content-type: application/json

{
    "sell": "Chaos Orb",
    "buy": "Exalted Orb"
}

###

POST http://trade.localhost:8888/trade
content-type: application/json

{
    "sell": "Chaos Orb",
    "buy": "Exalted Orb",
    "league": "Hardcore Archnemesis"
}

###

POST http://trade.localhost:8888/trade
content-type: application/json

{
    "sell": "Chaos Orb",
    "buy": "Exalted Orb",
    "limit": 3
}
