pstapi: External API
trade-store: {
  shape: cylinder
trade-store: PostgreSQL
}
indexer-store: PostgreSQL
trade-store: PostgreSQL
trade-api: Trade Store REST API
mq: {
  style: {
    fill: "#d63"
  }
  shape: circle
}
mq: RabbitMQ Broker

pstapi -> indexer: stream stash updates
indexer -> mq: publish updates
mq -> trade-ingest: consume updates
trade-ingest -> trade-store: store updates
trade-api -> trade-store: expose REST API

items: {
  shape: sql_table
  id: int {constraint: primary_key}
  item_id: text
  stash_id: text
  seller_account: text
  stock: int
  sell: text
  buy: text
  conversion_rate: real,
  created_at: timestamp
}
trade-store -> items
