name: Deploy
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name:
        env:
          DEPLOY_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        run: |
          ssh-add <(echo "$DEPLOY_PRIVATE_KEY")
          ssh $DEPLOY_USER@$DEPLOY_HOST "ls -la"

      - name: Deploy
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          host: ${{ secrets.DEPLOY_HOST }}
          user: ${{ secrets.DEPLOY_USER }}
          last_ssh: |
            set -ex
            cd /home/${{ secrets.DEPLOY_USER }}/deployment
            docker pull maximumstock2/indexer:latest
            docker-compose up -f docker-compose.production.yml -d
            echo "Successfully deployed"
