name: Deploy
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deployment
        env:
          DEPLOY_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          AGE_KEY: ${{ secrets.AGE_KEY }}
        run: |
          eval $(ssh-agent -s)
          ssh-add <(echo "$DEPLOY_PRIVATE_KEY")
          ssh -q -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST << EOF
            export AGE_KEY="$AGE_KEY"
            export ENV="production"

            set -ex
            echo "Environment: $ENV"

            # Need this to make sure we have the latest image
            docker pull maximumstock2/trade-api:latest
            docker pull maximumstock2/trade-ingest:latest
            docker pull maximumstock2/trade-indexer:latest

            cd deployment && git pull
            make config
            docker-compose -f docker-compose.yaml -f docker-compose.production.yaml build --force-rm reverse-proxy prometheus rabbitmq
            docker-compose -f docker-compose.yaml -f docker-compose.production.yaml build grafana
            make up-prod
            docker-compose -f docker-compose.yaml -f docker-compose.production.yaml logs --tail=1000 trade-api trade-store indexer
          EOF
      - name: Grafana Annotation
        env:
          GRAFANA_TOKEN: ${{ secrets.GRAFANA_TOKEN }}
        run: |
          curl -XPOST http://grafana.maximumstock.net/api/annotations \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $GRAFANA_TOKEN" \
            --data @- << EOF
            {
              "text": "Deployed backend services",
              "tags": [ "deployment" ]
            }EOF
